language: java
jdk: oraclejdk7
env:
    matrix:
    #- ANDROID_SDKS=android-8            ANDROID_TARGET=android-8   ANDROID_ABI=armeabi
    #- ANDROID_SDKS=android-10           ANDROID_TARGET=android-10  ANDROID_ABI=armeabi
    #- ANDROID_SDKS=sysimg-16            ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a
    - ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
before_install:
    # Create dummy keys
    - cp core/assets/secretkeys.properties.sample core/assets/secretkeys.properties

    # Install base Android SDK
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - wget http://dl.google.com/android/android-sdk_r22.6.2-linux.tgz
    - tar zxf android-sdk_r22.6.2-linux.tgz
    - export ANDROID_HOME=`pwd`/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    # Install required Android components.
    - echo y | android update sdk --filter platform-tools,build-tools-19.0.3,android-19,extra-android-support,extra-android-m2repository,$ANDROID_SDKS --no-ui -a --force
    - echo yes | android update sdk --filter android-19 --no-ui --force > /dev/null
    - echo yes | android update sdk --filter sysimg-19 --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-google-google_play_services --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-google-m2repository --no-ui --force > /dev/null

    # Create and start emulator
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &

before_script:
    # Make sure the emulator has started before running tests
    - ./wait_for_emulator

#script: mvn install -Pintegration-tests -Dandroid.device=test
script:
  - echo $TRAVIS_BUILD_DIR
  - TERM=dumb cd full;../gradlew connectedCheck
